package by.pvt.dudko.company.web.command.constant;

public enum Commands {
LOGIN,REGISTRATION,PAGE_ORDER,CLIENT_PAGE,MY_ORDERS,
CHANGE_CAR,CHANGE_TRIP,PAGES_BASE,ADMIN_EXIT,CHANGE_LOCALE,
CHANGE_COND_TRIP,CHANGE_COND_CAR,EXIT_ADMIN,NOT_CAR,RETURN,CLIENT_TRIP,DELETE_ACCOUNT
}
